disable deploy

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -287,58 +287,58 @@ jobs:
           ignore-unfixed: true
           vuln-type: 'os,library'
           severity: 'CRITICAL,HIGH'
-  deploy:
-    runs-on: ubuntu-latest
-    needs: [e2e_tests, unit_tests, isort, black, flake8, mypy, frontend_tests]
-    if: |
-      github.event_name == 'push' &&
-      (
-        github.ref == 'refs/heads/develop' ||
-        github.ref == 'refs/heads/staging' ||
-        github.ref == 'refs/heads/master' ||
-        github.ref == 'refs/heads/ephemeral-1' ||
-        github.ref == 'refs/heads/ephemeral-2' ||
-        github.ref == 'refs/heads/ephemeral-3'
-      )
-    steps:
-      - name: Trigger deploy
-        run: |
-          # TODO: make it prettier
-          if [ ${{ github.ref }} == 'refs/heads/develop' ]; then
-            pipelineId=1159
-          elif [ ${{ github.ref }} == 'refs/heads/staging' ]; then
-            pipelineId=1160
-          elif [ ${{ github.ref }} == 'refs/heads/master' ]; then
-            pipelineId=1161,1165
-          elif [ ${{ github.ref }} == 'refs/heads/ephemeral-1' ]; then
-            pipelineId=1164
-          elif [ ${{ github.ref }} == 'refs/heads/ephemeral-2' ]; then
-            pipelineId=1253
-          elif [ ${{ github.ref }} == 'refs/heads/ephemeral-3' ]; then
-            pipelineId=1283
-          else
-            echo "No pipeline to trigger for ref ${{ github.ref }}"
-            exit 0
-          fi
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: [e2e_tests, unit_tests, isort, black, flake8, mypy, frontend_tests]
+  #   if: |
+  #     github.event_name == 'push' &&
+  #     (
+  #       github.ref == 'refs/heads/develop' ||
+  #       github.ref == 'refs/heads/staging' ||
+  #       github.ref == 'refs/heads/master' ||
+  #       github.ref == 'refs/heads/ephemeral-1' ||
+  #       github.ref == 'refs/heads/ephemeral-2' ||
+  #       github.ref == 'refs/heads/ephemeral-3'
+  #     )
+  #   steps:
+  #     - name: Trigger deploy
+  #       run: |
+  #         # TODO: make it prettier
+  #         if [ ${{ github.ref }} == 'refs/heads/develop' ]; then
+  #           pipelineId=1159
+  #         elif [ ${{ github.ref }} == 'refs/heads/staging' ]; then
+  #           pipelineId=1160
+  #         elif [ ${{ github.ref }} == 'refs/heads/master' ]; then
+  #           pipelineId=1161,1165
+  #         elif [ ${{ github.ref }} == 'refs/heads/ephemeral-1' ]; then
+  #           pipelineId=1164
+  #         elif [ ${{ github.ref }} == 'refs/heads/ephemeral-2' ]; then
+  #           pipelineId=1253
+  #         elif [ ${{ github.ref }} == 'refs/heads/ephemeral-3' ]; then
+  #           pipelineId=1283
+  #         else
+  #           echo "No pipeline to trigger for ref ${{ github.ref }}"
+  #           exit 0
+  #         fi
 
-          IFS=',' read -ra pipelines <<< "$pipelineId"
-          for pipeline in "${pipelines[@]}"; do
-            jsonBody='{"variables": {"sha": {"isSecret": false, "value": "${{ github.sha }}"}, "tag": {"isSecret": false, "value": "core-${{ github.sha }}"}}}'
-            contentLength=$(echo -n $jsonBody | wc -c)
-            project=ICTD-HCT-MIS
-            organization=unicef
+  #         IFS=',' read -ra pipelines <<< "$pipelineId"
+  #         for pipeline in "${pipelines[@]}"; do
+  #           jsonBody='{"variables": {"sha": {"isSecret": false, "value": "${{ github.sha }}"}, "tag": {"isSecret": false, "value": "core-${{ github.sha }}"}}}'
+  #           contentLength=$(echo -n $jsonBody | wc -c)
+  #           project=ICTD-HCT-MIS
+  #           organization=unicef
 
-            echo Triggering deploy for pipeline $pipeline
-            echo JSON body: $jsonBody
+  #           echo Triggering deploy for pipeline $pipeline
+  #           echo JSON body: $jsonBody
 
-            curl -v -L \
-              -u ":${{ secrets.AZURE_PAT }}" \
-              -H "Content-Type: application/json" \
-              -H "Content-Length: $contentLength" \
-              -d "$jsonBody" \
-              https://dev.azure.com/$organization/$project/_apis/pipelines/$pipeline/runs?api-version=7.1-preview.1
-            if [ $? -ne 0 ]; then
-              echo "Failed to trigger deploy for pipeline $pipeline"
-              exit 1
-            fi
-          done
+  #           curl -v -L \
+  #             -u ":${{ secrets.AZURE_PAT }}" \
+  #             -H "Content-Type: application/json" \
+  #             -H "Content-Length: $contentLength" \
+  #             -d "$jsonBody" \
+  #             https://dev.azure.com/$organization/$project/_apis/pipelines/$pipeline/runs?api-version=7.1-preview.1
+  #           if [ $? -ne 0 ]; then
+  #             echo "Failed to trigger deploy for pipeline $pipeline"
+  #             exit 1
+  #           fi
+  #         done
